disabled_rules:
    - unused_closure_parameter
    - trailing_whitespace

opt_in_rules:
    - trailing_closure
    - force_unwrap

included:
    exzo
excluded:
    Pods

line_length:
    warning: 200
    error: 250
    ignores_function_declarations: false
    ignores_comments: true
    ignores_interpolated_strings: false
    ignores_urls: true
        
file_length:
    warning: 800
    error: 1000
    
force_cast: warning

comma: error

trailing_comma: error

vertical_whitespace: error
